public class LWCPaginitionControllerWrapper {
    public List<String> selectedFields;
    public String selectedObject;
    public Integer noOfRecord;
    public String fristRecId;
    public String lastRecId;
    public string nameFeild;
    public string lastRecName;
    public string firstRecName;
    public string sortByFeild;
    public string sortDirection;

}
/*
var args = {
    selectedFields : this.selectedFeilds,
    selectedObject:this.selectedObject,
    noOfRecord:this.noOfRecord,
    fristRecId:this.firstRecordId,
    lastRecId:this.lastRecordId,
    nameFeild:this.firstFeild,
    lastRecName:this.lastRecName,
    firstRecName:this.firstRecName,
    sortByFeild:this.sortBy,
    sortDirection:this.sortDirection
};*/